### ISSUE TITLE
Manifest Json not resolve path on first write

### ISSUE THREAD

**Issue by alexzvn** [alexzvn/amber#9]
Configure from `amber.config.ts` that contains something like `new Page('@/index.html')` will not resolve on first write on disk.
When using with dev browser, it can't load extension sometimes.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the ResolveAlias plugin to handle initial file resolution more robustly, and adjusted the browser setup process to ensure consistent extension loading.

You can review changes in this commit: https://github.com/mnmnk43434/alexzvn-amber-9/commit/d05b0519fc3068fd850de7f81e42d2b57b8a46aa.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
